### ISSUE TITLE
主页面无法加载

### ISSUE THREAD

**Issue by ginkin** [KKDYData/KokodayoData#100]
进入https://www.kokodayo.fun/
后主页面无法加载干员信息，使用无痕浏览或者清除cookie无法解决。
![image](https://user-images.githubusercontent.com/17687015/118613677-532f8280-b802-11eb-8596-fa50e8c07c67.png)

f12的报错信息是
![image](https://user-images.githubusercontent.com/17687015/118613722-5e82ae00-b802-11eb-95ec-fa4406d62dd5.png)

**Comment by odex21** [comment]
已经好了
