### ISSUE TITLE
兼容www域名

### ISSUE THREAD

**Issue by as168795** [KKDYData/KokodayoData#102]
使用的chromium 90内核浏览器全部不能正常加载数据了。F12发现是跨域报错，www.kokodayo.fun之于kokodayo.fun虽然是同样的顶级域名但现在也提示跨域了，3级域名的test.api.kokodayo.fun更是如此。大大辛苦了 望早日修复

**Comment by odex21** [comment]
主要是新的后端，现在限制了kokodayo.fun。
我是一直不建议用www访问的…

主要出于统计和成本方面的考量
