### ISSUE TITLE
从企鹅物流前往本站由于 Referrer 被禁止

### ISSUE THREAD

**Issue by GalvinGao** [KKDYData/KokodayoData#117]
由 https://penguin-stats.cn/about/links 前往 https://kokodayo.fun 由于 Referrer Policy 而被禁止

```
<Error>
<Code>AccessDenied</Code>
<Message>You are denied by bucket referer policy.</Message>
<RequestId>(redacted)</RequestId>
<HostId>kkdy-prod.oss-cn-hangzhou.aliyuncs.com</HostId>
<BucketName>kkdy-prod</BucketName>
</Error>
```

考虑将企鹅物流的域名 `penguin-stats.io` `penguin-stats.cn` 加入 Referrer 白名单？或者我们也可以发布一个在跳转时使用 `rel='noreferrer'` 的更新，但仍然在使用旧客户端的用户将继续无法使用本站x

**Comment by odex21** [comment]
已加白名单
